export type QuizReportAttempt = {
  id: string;
  name: string;
  email: string | null;
  rollNumber?: string | null;
  seatNumber?: string | null;
  score: number;
  totalQuestions: number;
  totalMaxPoints?: number | null; // sum of all question max_points for the session
  attemptedQuestions: number;
  correctAnswers: number;
  wrongAnswers: number;
  unattemptedQuestions: number;
  completed: boolean;
  startedAt?: string | null;
  completedAt: string | null;
  durationSeconds?: number | null;
};

export type QuizReportSession = {
  title: string;
  categoryLabel?: string;
  teacherName?: string;
  schoolName?: string;
  subjectLabel?: string;
  topicLabel?: string;
  createdAt: string;
  questionCount: number;
  attempts: QuizReportAttempt[];
};

export type QuizReportRow = QuizReportAttempt & {
  rank: number;
  percent: number;
};

export function getQuizReportRows(attempts: QuizReportAttempt[]): QuizReportRow[] {
  return attempts
    .slice()
    .sort((a, b) => {
      if (b.score !== a.score) return b.score - a.score;
      if (b.attemptedQuestions !== a.attemptedQuestions) {
        return b.attemptedQuestions - a.attemptedQuestions;
      }
      return a.name.localeCompare(b.name);
    })
    .map((a, index) => ({
      ...a,
      rank: index + 1,
      percent: Math.min(
        100,
        Math.round((a.score / Math.max(1, a.totalMaxPoints ?? a.totalQuestions)) * 100),
      ),
    }));
}

export function downloadQuizReportCsv(
  session: QuizReportSession,
  options?: { rows?: QuizReportRow[]; filterSummary?: string; watermark?: boolean },
) {
  const rows = options?.rows ?? getQuizReportRows(session.attempts);
  const headers = [
    "Position",
    "Name",
    "Email",
    "Roll Number",
    "Seat Number",
    "Points",
    "Correct",
    "Wrong",
    "Unattempted",
    "Attempted Questions",
    "Total Questions",
    "Percent",
    "Duration",
    "Status",
    "Completed At",
  ];
  const NOT_SPECIFIED = "Not specified";
  const csv = [
    [`Quiz Report: ${session.title}`],
    [`Teacher: ${session.teacherName || NOT_SPECIFIED}`],
    [`School/Organization: ${session.schoolName || NOT_SPECIFIED}`],
    [`Subject: ${session.subjectLabel || session.categoryLabel || NOT_SPECIFIED}`],
    [`Topic: ${session.topicLabel || NOT_SPECIFIED}`],
    [`Category: ${session.categoryLabel || "Uncategorised"}`],
    options?.filterSummary ? [`Filters: ${options.filterSummary}`] : null,
    [`Generated: ${new Date().toLocaleString()}`],
    options?.watermark !== false ? [`Generated by EvaluTease — https://evalutease.com`] : null,
    [],
    headers,
    ...rows.map((r) => [
      r.rank,
      r.name,
      r.email ?? "",
      r.rollNumber ?? "",
      r.seatNumber ?? "",
      r.score,
      r.correctAnswers,
      r.wrongAnswers,
      r.unattemptedQuestions,
      r.attemptedQuestions,
      r.totalQuestions,
      `${r.percent}%`,
      formatDuration(r.durationSeconds ?? null),
      r.completed ? "Completed" : "Did not finish",
      r.completedAt ? new Date(r.completedAt).toLocaleString() : "",
    ]),
  ]
    .flatMap((row) => (row !== null ? [row.map(csvCell).join(",")] : []))
    .join("\n");

  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `${slugify(session.title)}-quiz-report.csv`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export function printQuizResults(session: QuizReportSession) {
  const rows = getQuizReportRows(session.attempts);
  const now = new Date().toLocaleString();

  const tableRows = rows
    .map(
      (r, i) => `
    <tr style="background:${i % 2 === 0 ? "#ffffff" : "#f9fafb"};">
      <td style="text-align:center;font-weight:700;">${r.rank}</td>
      <td><strong>${r.name}</strong></td>
      <td>${r.rollNumber || "-"}</td>
      <td>${r.email || "-"}</td>
      <td style="text-align:center;">${r.attemptedQuestions}</td>
      <td style="text-align:center;color:#16a34a;font-weight:700;">${r.correctAnswers}</td>
      <td style="text-align:center;color:#dc2626;font-weight:700;">${r.wrongAnswers}</td>
      <td style="text-align:center;">${formatDuration(r.durationSeconds ?? null)}</td>
      <td style="text-align:center;">${r.unattemptedQuestions}</td>
    </tr>`,
    )
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Results — ${session.title}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: Arial, sans-serif; font-size: 11px; color: #111; background: #fff; padding: 20px; }

    /* Top bar */
    .top-bar { background: #6d28d9; color: #fff; padding: 14px 20px; border-radius: 8px 8px 0 0; display: flex; justify-content: space-between; align-items: center; }
    .top-bar .app-name { font-size: 18px; font-weight: 700; letter-spacing: -0.5px; }
    .top-bar .app-sub { font-size: 10px; opacity: 0.8; margin-top: 2px; }
    .top-bar .print-date { font-size: 10px; opacity: 0.8; text-align: right; }

    /* Info grid */
    .info-grid { border: 1px solid #e5e7eb; border-top: none; padding: 14px 20px; display: grid; grid-template-columns: repeat(2, 1fr); gap: 0; }
    .info-grid .row { display: contents; }
    .info-item { padding: 6px 10px 6px 0; border-bottom: 1px solid #f3f4f6; }
    .info-item .lbl { font-size: 9px; text-transform: uppercase; letter-spacing: 0.5px; color: #9ca3af; }
    .info-item .val { font-size: 12px; font-weight: 600; margin-top: 1px; color: #111; }
    .info-item.full { grid-column: 1 / -1; }

    /* Table */
    .table-wrap { margin-top: 14px; border: 1px solid #e5e7eb; border-radius: 6px; overflow: hidden; }
    table { width: 100%; border-collapse: collapse; font-size: 10px; }
    thead tr { background: #6d28d9; color: #fff; }
    thead th { padding: 8px 8px; text-align: left; font-size: 9px; text-transform: uppercase; letter-spacing: 0.4px; white-space: nowrap; }
    thead th.center { text-align: center; }
    tbody td { padding: 6px 8px; border-bottom: 1px solid #e5e7eb; vertical-align: middle; }
    tbody tr:last-child td { border-bottom: none; }

    /* Signature */
    .signature { margin-top: 20px; border-top: 2px solid #6d28d9; padding-top: 14px; display: flex; justify-content: space-between; align-items: flex-end; }
    .sig-left .greeting { font-size: 11px; color: #374151; margin-bottom: 3px; }
    .sig-left .brand { font-size: 17px; font-weight: 700; color: #6d28d9; margin-bottom: 6px; }
    .sig-left .contact { font-size: 10px; color: #6b7280; line-height: 1.8; }
    .sig-right { font-size: 9px; color: #9ca3af; text-align: right; line-height: 1.7; }

    @media print {
      body { padding: 8px; }
      @page { margin: 10mm; size: A4 landscape; }
    }
  </style>
</head>
<body>

  <!-- Header -->
  <div class="top-bar">
    <div>
      <div class="app-name">EvaluTease</div>
      <div class="app-sub">Quiz Results Report</div>
    </div>
    <div class="print-date">
      <div>Printed: ${now}</div>
      <div>Total Participants: ${rows.length}</div>
    </div>
  </div>

  <!-- Session info -->
  <div class="info-grid">
    <div class="info-item">
      <div class="lbl">Company / School</div>
      <div class="val">${session.schoolName || "Not specified"}</div>
    </div>
    <div class="info-item">
      <div class="lbl">Host / Teacher</div>
      <div class="val">${session.teacherName || "Not specified"}</div>
    </div>
    <div class="info-item full">
      <div class="lbl">Quiz Topic</div>
      <div class="val">${session.title}${session.topicLabel ? " — " + session.topicLabel : ""}</div>
    </div>
    <div class="info-item">
      <div class="lbl">Subject</div>
      <div class="val">${session.subjectLabel || session.categoryLabel || "Not specified"}</div>
    </div>
    <div class="info-item">
      <div class="lbl">Total Questions</div>
      <div class="val">${session.questionCount}</div>
    </div>
  </div>

  <!-- Results table -->
  <div class="table-wrap">
    <table>
      <thead>
        <tr>
          <th class="center">Rank</th>
          <th>Participant Name</th>
          <th>Roll Number</th>
          <th>Email</th>
          <th class="center">Attempted</th>
          <th class="center">Correct</th>
          <th class="center">Wrong</th>
          <th class="center">Total Time</th>
          <th class="center">Unattempted</th>
        </tr>
      </thead>
      <tbody>${tableRows}</tbody>
    </table>
  </div>

  <!-- BabulTech Signature -->
  <div class="signature">
    <div class="sig-left">
      <div class="greeting">Warm &amp; Best Regards,</div>
      <div class="brand">BabulQ</div>
      <div class="contact">
        📞 +92 310 2700403<br/>
        ✉️ contact@babultech.com<br/>
        📍 <a href="https://maps.app.goo.gl/68znfMTx4ar17ipD9" style="color:#6d28d9;text-decoration:none;">IDC Office, Islamabad — View on Maps</a>
      </div>
    </div>
    <div class="sig-right">
      <div>© 2025 BabulTech · All rights reserved</div>
      <div>evalutease.com</div>
    </div>
  </div>

  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`;

  const win = window.open("", "_blank", "width=1100,height=800");
  if (!win) return;
  win.document.write(html);
  win.document.close();
}

function csvCell(value: string | number) {
  const text = String(value);
  if (!/[",\n]/.test(text)) return text;
  return `"${text.replace(/"/g, '""')}"`;
}

function slugify(value: string) {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "quiz"
  );
}

export function formatDuration(seconds: number | null | undefined): string {
  if (seconds === null || seconds === undefined || Number.isNaN(seconds) || seconds < 0) return "-";
  if (seconds < 60) return `${Math.round(seconds)}s`;
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds - m * 60);
  if (m < 60) return s ? `${m}m ${s}s` : `${m}m`;
  const h = Math.floor(m / 60);
  const mm = m - h * 60;
  return mm ? `${h}h ${mm}m` : `${h}h`;
}
