import type { PlanInfo, PlanSlug, PlanTier } from "./types";

export const FREE_PLAN: PlanInfo = {
  id: "",
  slug: "individual_starter",
  tier: "individual",
  name: "Starter",
  description: "Free plan",
  price_pkr: 0,
  credits_per_month: 0,
  quizzes_per_day: 3,
  scheduled_quizzes_per_day: 1,
  participants_per_session: 50,
  participants_total: 50,
  question_bank: 100,
  sessions_total: -1,
  max_hosts: 1,
  ai_calls_per_day: 0,
  ai_enabled: false,
  custom_branding: false,
  white_label: false,
  ai_interview: false,
  ai_coding_test: false,
  watermark_enabled: true,
  file_export_watermark: true,
  email_template_allowed: false,
  can_buy_credits: false,
  trial_days: 0,
  trial_ai_calls: 0,
  credit_cost_ai_10q: 3,
  credit_cost_ai_tf_10q: 3,
  credit_cost_ai_short_10q: 5,
  credit_cost_ai_long_10q: 10,
  credit_cost_ai_mix_10q: 6,
  credit_cost_ai_scan: 2,
  credit_cost_ai_interview: 5,
  credit_cost_ai_coding: 5,
  credit_cost_ai_grade_short: 1,
  credit_cost_ai_grade_long: 3,
  credit_cost_extra_quiz: 1,
  credit_cost_extra_participants: 1,
  credit_cost_session_launch: 0,
  credit_cost_export: 0,
  features_list: [],
};

export function rowToPlan(raw: Record<string, unknown>): PlanInfo {
  return {
    id: raw.id as string,
    slug: raw.slug as PlanSlug,
    tier: raw.tier as PlanTier,
    name: raw.name as string,
    description: (raw.description as string) ?? "",
    price_pkr: (raw.price_pkr as number) ?? 0,
    credits_per_month: (raw.credits_per_month as number) ?? 0,
    quizzes_per_day: (raw.quizzes_per_day as number) ?? 3,
    scheduled_quizzes_per_day: (raw.scheduled_quizzes_per_day as number) ?? 1,
    participants_per_session: (raw.participants_per_session as number) ?? 50,
    participants_total: (raw.participants_total as number) ?? 50,
    question_bank: (raw.question_bank as number) ?? 100,
    sessions_total: (raw.sessions_total as number) ?? -1,
    max_hosts: (raw.max_hosts as number) ?? 1,
    ai_calls_per_day: (raw.ai_calls_per_day as number) ?? 0,
    ai_enabled: (raw.ai_enabled as boolean) ?? false,
    custom_branding: (raw.custom_branding as boolean) ?? false,
    white_label: (raw.white_label as boolean) ?? false,
    ai_interview: (raw.ai_interview as boolean) ?? false,
    ai_coding_test: (raw.ai_coding_test as boolean) ?? false,
    watermark_enabled: (raw.watermark_enabled as boolean) ?? true,
    file_export_watermark: (raw.file_export_watermark as boolean) ?? true,
    email_template_allowed: (raw.email_template_allowed as boolean) ?? false,
    can_buy_credits: (raw.can_buy_credits as boolean) ?? false,
    trial_days: (raw.trial_days as number) ?? 0,
    trial_ai_calls: (raw.trial_ai_calls as number) ?? 0,
    credit_cost_ai_10q: (raw.credit_cost_ai_10q as number) ?? 3,
    credit_cost_ai_tf_10q: (raw.credit_cost_ai_tf_10q as number) ?? 3,
    credit_cost_ai_short_10q: (raw.credit_cost_ai_short_10q as number) ?? 5,
    credit_cost_ai_long_10q: (raw.credit_cost_ai_long_10q as number) ?? 10,
    credit_cost_ai_mix_10q: (raw.credit_cost_ai_mix_10q as number) ?? 6,
    credit_cost_ai_scan: (raw.credit_cost_ai_scan as number) ?? 2,
    credit_cost_ai_interview: (raw.credit_cost_ai_interview as number) ?? 5,
    credit_cost_ai_coding: (raw.credit_cost_ai_coding as number) ?? 5,
    credit_cost_ai_grade_short: (raw.credit_cost_ai_grade_short as number) ?? 1,
    credit_cost_ai_grade_long: (raw.credit_cost_ai_grade_long as number) ?? 3,
    credit_cost_extra_quiz: (raw.credit_cost_extra_quiz as number) ?? 1,
    credit_cost_extra_participants: (raw.credit_cost_extra_participants as number) ?? 1,
    credit_cost_session_launch: (raw.credit_cost_session_launch as number) ?? 0,
    credit_cost_export: (raw.credit_cost_export as number) ?? 0,
    features_list: (raw.features_list as string[]) ?? [],
  };
}
