/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QCodeRouteImport } from './routes/q.$code'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppSessionsRouteImport } from './routes/_app/sessions'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppParticipantTypesRouteImport } from './routes/_app/participant-types'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCategoriesRouteImport } from './routes/_app/categories'
import { Route as AppSessionsNewRouteImport } from './routes/_app/sessions.new'
import { Route as AppParticipantTypesTypeIdRouteImport } from './routes/_app/participant-types.$typeId'
import { Route as AppCategoriesCategoryIdRouteImport } from './routes/_app/categories.$categoryId'
import { Route as AppParticipantTypesTypeIdSubIdRouteImport } from './routes/_app/participant-types.$typeId.$subId'
import { Route as AppCategoriesCategoryIdSubIdRouteImport } from './routes/_app/categories.$categoryId.$subId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QCodeRoute = QCodeRouteImport.update({
  id: '/q/$code',
  path: '/q/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsRoute = AppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppParticipantTypesRoute = AppParticipantTypesRouteImport.update({
  id: '/participant-types',
  path: '/participant-types',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionsNewRoute = AppSessionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSessionsRoute,
} as any)
const AppParticipantTypesTypeIdRoute =
  AppParticipantTypesTypeIdRouteImport.update({
    id: '/$typeId',
    path: '/$typeId',
    getParentRoute: () => AppParticipantTypesRoute,
  } as any)
const AppCategoriesCategoryIdRoute = AppCategoriesCategoryIdRouteImport.update({
  id: '/$categoryId',
  path: '/$categoryId',
  getParentRoute: () => AppCategoriesRoute,
} as any)
const AppParticipantTypesTypeIdSubIdRoute =
  AppParticipantTypesTypeIdSubIdRouteImport.update({
    id: '/$subId',
    path: '/$subId',
    getParentRoute: () => AppParticipantTypesTypeIdRoute,
  } as any)
const AppCategoriesCategoryIdSubIdRoute =
  AppCategoriesCategoryIdSubIdRouteImport.update({
    id: '/$subId',
    path: '/$subId',
    getParentRoute: () => AppCategoriesCategoryIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AppCategoriesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/participant-types': typeof AppParticipantTypesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/q/$code': typeof QCodeRoute
  '/categories/$categoryId': typeof AppCategoriesCategoryIdRouteWithChildren
  '/participant-types/$typeId': typeof AppParticipantTypesTypeIdRouteWithChildren
  '/sessions/new': typeof AppSessionsNewRoute
  '/categories/$categoryId/$subId': typeof AppCategoriesCategoryIdSubIdRoute
  '/participant-types/$typeId/$subId': typeof AppParticipantTypesTypeIdSubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/categories': typeof AppCategoriesRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/participant-types': typeof AppParticipantTypesRouteWithChildren
  '/reports': typeof AppReportsRoute
  '/sessions': typeof AppSessionsRouteWithChildren
  '/settings': typeof AppSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/q/$code': typeof QCodeRoute
  '/categories/$categoryId': typeof AppCategoriesCategoryIdRouteWithChildren
  '/participant-types/$typeId': typeof AppParticipantTypesTypeIdRouteWithChildren
  '/sessions/new': typeof AppSessionsNewRoute
  '/categories/$categoryId/$subId': typeof AppCategoriesCategoryIdSubIdRoute
  '/participant-types/$typeId/$subId': typeof AppParticipantTypesTypeIdSubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/categories': typeof AppCategoriesRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/participant-types': typeof AppParticipantTypesRouteWithChildren
  '/_app/reports': typeof AppReportsRoute
  '/_app/sessions': typeof AppSessionsRouteWithChildren
  '/_app/settings': typeof AppSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/q/$code': typeof QCodeRoute
  '/_app/categories/$categoryId': typeof AppCategoriesCategoryIdRouteWithChildren
  '/_app/participant-types/$typeId': typeof AppParticipantTypesTypeIdRouteWithChildren
  '/_app/sessions/new': typeof AppSessionsNewRoute
  '/_app/categories/$categoryId/$subId': typeof AppCategoriesCategoryIdSubIdRoute
  '/_app/participant-types/$typeId/$subId': typeof AppParticipantTypesTypeIdSubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/dashboard'
    | '/participant-types'
    | '/reports'
    | '/sessions'
    | '/settings'
    | '/invite/$token'
    | '/q/$code'
    | '/categories/$categoryId'
    | '/participant-types/$typeId'
    | '/sessions/new'
    | '/categories/$categoryId/$subId'
    | '/participant-types/$typeId/$subId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/categories'
    | '/dashboard'
    | '/participant-types'
    | '/reports'
    | '/sessions'
    | '/settings'
    | '/invite/$token'
    | '/q/$code'
    | '/categories/$categoryId'
    | '/participant-types/$typeId'
    | '/sessions/new'
    | '/categories/$categoryId/$subId'
    | '/participant-types/$typeId/$subId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/categories'
    | '/_app/dashboard'
    | '/_app/participant-types'
    | '/_app/reports'
    | '/_app/sessions'
    | '/_app/settings'
    | '/invite/$token'
    | '/q/$code'
    | '/_app/categories/$categoryId'
    | '/_app/participant-types/$typeId'
    | '/_app/sessions/new'
    | '/_app/categories/$categoryId/$subId'
    | '/_app/participant-types/$typeId/$subId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  QCodeRoute: typeof QCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$code': {
      id: '/q/$code'
      path: '/q/$code'
      fullPath: '/q/$code'
      preLoaderRoute: typeof QCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions': {
      id: '/_app/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AppSessionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/participant-types': {
      id: '/_app/participant-types'
      path: '/participant-types'
      fullPath: '/participant-types'
      preLoaderRoute: typeof AppParticipantTypesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sessions/new': {
      id: '/_app/sessions/new'
      path: '/new'
      fullPath: '/sessions/new'
      preLoaderRoute: typeof AppSessionsNewRouteImport
      parentRoute: typeof AppSessionsRoute
    }
    '/_app/participant-types/$typeId': {
      id: '/_app/participant-types/$typeId'
      path: '/$typeId'
      fullPath: '/participant-types/$typeId'
      preLoaderRoute: typeof AppParticipantTypesTypeIdRouteImport
      parentRoute: typeof AppParticipantTypesRoute
    }
    '/_app/categories/$categoryId': {
      id: '/_app/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/categories/$categoryId'
      preLoaderRoute: typeof AppCategoriesCategoryIdRouteImport
      parentRoute: typeof AppCategoriesRoute
    }
    '/_app/participant-types/$typeId/$subId': {
      id: '/_app/participant-types/$typeId/$subId'
      path: '/$subId'
      fullPath: '/participant-types/$typeId/$subId'
      preLoaderRoute: typeof AppParticipantTypesTypeIdSubIdRouteImport
      parentRoute: typeof AppParticipantTypesTypeIdRoute
    }
    '/_app/categories/$categoryId/$subId': {
      id: '/_app/categories/$categoryId/$subId'
      path: '/$subId'
      fullPath: '/categories/$categoryId/$subId'
      preLoaderRoute: typeof AppCategoriesCategoryIdSubIdRouteImport
      parentRoute: typeof AppCategoriesCategoryIdRoute
    }
  }
}

interface AppCategoriesCategoryIdRouteChildren {
  AppCategoriesCategoryIdSubIdRoute: typeof AppCategoriesCategoryIdSubIdRoute
}

const AppCategoriesCategoryIdRouteChildren: AppCategoriesCategoryIdRouteChildren =
  {
    AppCategoriesCategoryIdSubIdRoute: AppCategoriesCategoryIdSubIdRoute,
  }

const AppCategoriesCategoryIdRouteWithChildren =
  AppCategoriesCategoryIdRoute._addFileChildren(
    AppCategoriesCategoryIdRouteChildren,
  )

interface AppCategoriesRouteChildren {
  AppCategoriesCategoryIdRoute: typeof AppCategoriesCategoryIdRouteWithChildren
}

const AppCategoriesRouteChildren: AppCategoriesRouteChildren = {
  AppCategoriesCategoryIdRoute: AppCategoriesCategoryIdRouteWithChildren,
}

const AppCategoriesRouteWithChildren = AppCategoriesRoute._addFileChildren(
  AppCategoriesRouteChildren,
)

interface AppParticipantTypesTypeIdRouteChildren {
  AppParticipantTypesTypeIdSubIdRoute: typeof AppParticipantTypesTypeIdSubIdRoute
}

const AppParticipantTypesTypeIdRouteChildren: AppParticipantTypesTypeIdRouteChildren =
  {
    AppParticipantTypesTypeIdSubIdRoute: AppParticipantTypesTypeIdSubIdRoute,
  }

const AppParticipantTypesTypeIdRouteWithChildren =
  AppParticipantTypesTypeIdRoute._addFileChildren(
    AppParticipantTypesTypeIdRouteChildren,
  )

interface AppParticipantTypesRouteChildren {
  AppParticipantTypesTypeIdRoute: typeof AppParticipantTypesTypeIdRouteWithChildren
}

const AppParticipantTypesRouteChildren: AppParticipantTypesRouteChildren = {
  AppParticipantTypesTypeIdRoute: AppParticipantTypesTypeIdRouteWithChildren,
}

const AppParticipantTypesRouteWithChildren =
  AppParticipantTypesRoute._addFileChildren(AppParticipantTypesRouteChildren)

interface AppSessionsRouteChildren {
  AppSessionsNewRoute: typeof AppSessionsNewRoute
}

const AppSessionsRouteChildren: AppSessionsRouteChildren = {
  AppSessionsNewRoute: AppSessionsNewRoute,
}

const AppSessionsRouteWithChildren = AppSessionsRoute._addFileChildren(
  AppSessionsRouteChildren,
)

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppParticipantTypesRoute: typeof AppParticipantTypesRouteWithChildren
  AppReportsRoute: typeof AppReportsRoute
  AppSessionsRoute: typeof AppSessionsRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppParticipantTypesRoute: AppParticipantTypesRouteWithChildren,
  AppReportsRoute: AppReportsRoute,
  AppSessionsRoute: AppSessionsRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  QCodeRoute: QCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
