create table if not exists public.promo_codes (
  id                   uuid primary key default gen_random_uuid(),
  code                 text not null unique,
  description          text,
  discount_percent     numeric(5,2),
  discount_fixed_cents int,
  applies_to_slugs     text[] not null default '{}',
  max_uses             int,
  uses_count           int not null default 0,
  expires_at           timestamptz,
  is_active            boolean not null default true,
  created_at           timestamptz not null default now()
);

alter table public.promo_codes enable row level security;

drop policy if exists "Authenticated users can validate promo codes" on public.promo_codes;
drop policy if exists "Admins manage promo codes" on public.promo_codes;

create policy "Authenticated users can validate promo codes"
  on public.promo_codes for select
  using (auth.role() = 'authenticated');

create policy "Admins manage promo codes"
  on public.promo_codes for all
  using  (public.has_role(auth.uid(), 'admin'))
  with check (public.has_role(auth.uid(), 'admin'));

insert into public.promo_codes (code, description, discount_percent, applies_to_slugs, max_uses, expires_at)
values
  ('WELCOME20', '20% off any paid plan', 20, '{}', 100, now() + interval '1 year'),
  ('PROEDU50',  '50% off Pro plan',      50, '{pro}', 50, now() + interval '6 months')
on conflict (code) do nothing;

-- Reset plans (Stripe price IDs are now auto-generated by the app when admin saves a plan)
DELETE FROM user_subscriptions;
DELETE FROM plans;

INSERT INTO plans (slug, name, description, price_monthly, price_yearly, is_active, sort_order, features, limits, stripe_price_id_monthly, stripe_price_id_yearly)
VALUES
  (
    'free', 'Free', 'Get started at no cost',
    0, 0, true, 1,
    '["5 quizzes per day", "3 AI calls per day", "Up to 30 participants", "100 question bank", "20 total sessions"]'::jsonb,
    '{"quizzes_per_day": 5, "ai_calls_per_day": 3, "participants_per_session": 30, "question_bank": 100, "sessions_total": 20}'::jsonb,
    null, null
  ),
  (
    'pro', 'Pro', 'For educators and trainers',
    19, 149, true, 2,
    '["50 quizzes per day", "30 AI calls per day", "Up to 200 participants", "1000 question bank", "Unlimited sessions", "Priority support"]'::jsonb,
    '{"quizzes_per_day": 50, "ai_calls_per_day": 30, "participants_per_session": 200, "question_bank": 1000, "sessions_total": -1}'::jsonb,
    null, null
  ),
  (
    'enterprise', 'Enterprise', 'For large organizations',
    79, 599, true, 3,
    '["Unlimited quizzes", "Unlimited AI calls", "Unlimited participants", "Unlimited question bank", "Unlimited sessions", "Dedicated support", "Custom branding"]'::jsonb,
    '{"quizzes_per_day": -1, "ai_calls_per_day": -1, "participants_per_session": -1, "question_bank": -1, "sessions_total": -1}'::jsonb,
    null, null
  );
